---
responses:
  "That tweet was hurtful to people I care about. You should try to use different language.": 
    - '#uglygirlsarenotallowed'  
    - '#slut'
    - '#ihatefemaleswho'
    - '#fatbitch'
    - '#bitches'
#     - '#mensrights'
  "Thanks for being an awesome feminist!":
    - '#fembottest'

blacklist_text: "@fembotbot i'm sorry for the language I used. it was hurtful to others, and i'm ashamed. i'm educating myself on being a better human being."

